name: Tests

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: [ windows-latest ]
    steps:
      - name: Full Checkout
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
          persist-credentials: false
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Build
        run: dotnet run --project .\engine\Tools\SboxBuild\SboxBuild.csproj -- build --config Developer

      - name: Test
        run: dotnet run --project .\engine\Tools\SboxBuild\SboxBuild.csproj -- test --filter "TestCategory!=LiveBackend"

  tests-linux:
    runs-on: ubuntu-24.04
    steps:
      - name: Full Checkout
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
          persist-credentials: false
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Build
        run: dotnet run --project ./engine/Tools/SboxBuild/SboxBuild.csproj -- build --config Developer

      - name: Test (unit)
        working-directory: ./engine
        run: dotnet test Tests/Sandbox.Test.Unit/Sandbox.Test.Unit.csproj --no-build --logger "console;verbosity=normal;consoleLoggerParameters=ErrorsOnly" -c Release --filter "TestCategory!=LiveBackend"

      - name: Test (engine)
        working-directory: ./engine
        env:
          FACEPUNCH_ENGINE: ${{ github.workspace }}/game
        run: dotnet test Tests/Sandbox.Test.Engine/Sandbox.Test.Engine.csproj --no-build --logger "console;verbosity=normal;consoleLoggerParameters=ErrorsOnly" -c Release --filter "TestCategory!=LiveBackend"
